/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportRouteImport } from './routes/report'
import { Route as HandoffClaimIdRouteImport } from './routes/handoff.$claimId'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffClaimIdRoute = HandoffClaimIdRouteImport.update({
  id: '/handoff/$claimId',
  path: '/handoff/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/handoff/$claimId': typeof HandoffClaimIdRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/handoff/$claimId': typeof HandoffClaimIdRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/handoff/$claimId': typeof HandoffClaimIdRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/login'
    | '/profile'
    | '/report'
    | '/handoff/$claimId'
    | '/items/$itemId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/login'
    | '/profile'
    | '/report'
    | '/handoff/$claimId'
    | '/items/$itemId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/login'
    | '/profile'
    | '/report'
    | '/handoff/$claimId'
    | '/items/$itemId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  HandoffClaimIdRoute: typeof HandoffClaimIdRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$claimId': {
      id: '/handoff/$claimId'
      path: '/handoff/$claimId'
      fullPath: '/handoff/$claimId'
      preLoaderRoute: typeof HandoffClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  HandoffClaimIdRoute: HandoffClaimIdRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
